[package]
name = "phoenix-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] } 
config = "0.15.11"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = {version = "1.44.1", features = ["full"]}
tokio-postgres = "0.7.13"
